# Generated by Django 4.2.2 on 2023-06-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
