# Generated by Django 4.2.2 on 2023-07-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_alter_chat_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
