# Generated by Django 4.2.2 on 2023-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, to='feed.photo'),
        ),
    ]
