# Generated by Django 4.2.2 on 2023-07-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'content']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
